BEGIN;

-- AlterTable
ALTER TABLE "beer_data"."beers" RENAME COLUMN "style_id" TO "legacy_style_id";

-- DropForeignKey
ALTER TABLE "beer_data"."beers" DROP CONSTRAINT "beers_style_id_fkey";

-- AlterTable
ALTER TABLE "beer_data"."beers" ADD COLUMN "style_id" TEXT;

-- AddForeignKey
ALTER TABLE "beer_data"."beers" ADD CONSTRAINT "beers_style_id_fkey" FOREIGN KEY ("style_id") REFERENCES "beer_data"."styles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- UpdateData
UPDATE "beer_data"."beers"
SET "style_id" =
  CASE
    WHEN "legacy_style_id" = 'g3OiPVP4z1TBuXpZL_VkT' THEN '9cOts-yCYPCMYzUoFYlwN'
    WHEN "legacy_style_id" = '2bn9uELzdCOw0yPUPdTPU' THEN 'VzdZnjcdgqMf8PP-zlZeA'
    WHEN "legacy_style_id" = 'TNTMjsP6fyhWyAlbH46jJ' THEN '9cOts-yCYPCMYzUoFYlwN'
    WHEN "legacy_style_id" = '3cnq140zSuc0YhWJostg3' THEN 'E1vWQwVzV2JrhEghxAV7p'
    WHEN "legacy_style_id" = 'FXncnuHzQcEkfMT8IVUhL' THEN '-cody4qwF3YwYvd2ePvFd'
    WHEN "legacy_style_id" = 'FE4itsMc2hV74naPnZux_' THEN 'MmKK7WUTr9d5tjPbGUxwD'
    WHEN "legacy_style_id" = 'wgetbKbyuSp8ciKn3v_f_' THEN 'VEKn-i-4rE1zIe4OzSiY1'
    WHEN "legacy_style_id" = 'Ie1SF_S5EQkeruT2ZwOkh' THEN '9cOts-yCYPCMYzUoFYlwN'
    WHEN "legacy_style_id" = 'jb0jpjQPZuKJiVlm6EhNK' THEN 'GFfDn5GJebv9tIkZ2KlOB'
    WHEN "legacy_style_id" = 'dM2uNWypp6S8sNthtRtaC' THEN 'VJLb10s1QqbEKmQQbYAi0'
    WHEN "legacy_style_id" = 'St7w0bf_FCFVJ7geBLUni' THEN '_IXjud2IY_bEJ3G_sFMg_'
    WHEN "legacy_style_id" = 'Y6P4AIhd3LiZ3oCe0ggsn' THEN 'fQS8C7J7wGRseFtIoWaa7'
    WHEN "legacy_style_id" = '-f9tdHqDZBa7NluOgWxPp' THEN 'tvPeFLr-NcV8psLfGahOG'
    WHEN "legacy_style_id" = 'goMd40r4eZX5JV__NcLIW' THEN 'tvPeFLr-NcV8psLfGahOG'
    WHEN "legacy_style_id" = '3QH-TIVmJeyEPu4pR0SsJ' THEN 'tvPeFLr-NcV8psLfGahOG'
    WHEN "legacy_style_id" = 'tE7QQ557IuMzGwgs2yKDR' THEN '3IcAttyALX9i6H68UIy--'
    WHEN "legacy_style_id" = 'x6mOlbEUtLev7CmRJBhSt' THEN '0BSUuPbCwRQiAPxrPFsHe'
    WHEN "legacy_style_id" = 'QS5xFmKT9AXy4ISh2kTHf' THEN 'abRFQVWf5CuJKe7A7ZZKh'
    WHEN "legacy_style_id" = 'GAp9Rh0v9N3qI6bTvJHRu' THEN 'vsk8kU2ghfnnkJlZ6mq0M'
    WHEN "legacy_style_id" = 'gS4VUSPel-80-HwcBGKeN' THEN 'AXrHELPTdk9ucLJ0hnkEI'
    WHEN "legacy_style_id" = '2Ptku0e8eH1IE1oWYrkke' THEN '1oUgBT_xktAkAMsOE_Ipm'
    WHEN "legacy_style_id" = 'NLoP5Znhc6skTrUGfE2O8' THEN 'UoYaa4t8TEgfYbm5_t-Fz'
    WHEN "legacy_style_id" = '-TdvK0wgR-sEK9-20CRLJ' THEN 'UoYaa4t8TEgfYbm5_t-Fz'
    WHEN "legacy_style_id" = 'Pyj862GzVLmzcwnEDV2iw' THEN 'oUpWohhyZwr8w4xk_5qZQ'
    WHEN "legacy_style_id" = 'oFnRedtn6nskVvrzex4av' THEN 'cYUiHXPquClF7mn8eB2ki'
    WHEN "legacy_style_id" = '08x2nnAqfTCDQ5XxMVs7o' THEN 'J-EUepQtz2Db_er5cTtoW'
    WHEN "legacy_style_id" = 'tU8_tQEiAYrLofVa3Ntua' THEN 'M3VcRbGCCi6zDx2EVT0yZ'
    WHEN "legacy_style_id" = '0o79nZ9zdZRxJfNnldenA' THEN 'Xwpq9XRp3E4EbBEXf9voV'
    WHEN "legacy_style_id" = '_gEmZLbvQGxUKp3sxbvgs' THEN 'wMVAvfsjIljJWO3pJO5rr'
    WHEN "legacy_style_id" = '0DznX-jUZPcRopDHPfa9B' THEN 'Gt0vb7pdFhOVIK39rgn7C'
    WHEN "legacy_style_id" = '_VG4z-q7NHSnYTuPf-9He' THEN 'NkMbiiBjOdViNwYlJyD6C'
    WHEN "legacy_style_id" = '0B1mzsqB_GKlWttmn8ka6' THEN 'XPZZWJrz0WyrcDNRftoYL'
    WHEN "legacy_style_id" = 'y_XCjJLo1Sw7rKV64vwTw' THEN 'f0iMUkt3GpDJ6kzNn-krK'
    WHEN "legacy_style_id" = 'Pw-zY4GPidBxVJbMhW3y8' THEN '134Hrge0UHVGY8Tl-cY64'
    WHEN "legacy_style_id" = 'vndxug2e7gJZbRQu1Orw8' THEN 'g0ySyTa0Zi6zTGhSbTzSh'
    WHEN "legacy_style_id" = '_QTdCRK79owUeuGI_cDsr' THEN 'QjrSyoX0AYTZVJrVlEgZH'
    WHEN "legacy_style_id" = 'ZHeqhj_q084F7pMcjKiCq' THEN 'poTQ1hrfsnvG4RGjHOPRW'
    WHEN "legacy_style_id" = 'YMv8DZEkBMGF-lX7oLYiF' THEN 'poTQ1hrfsnvG4RGjHOPRW'
    WHEN "legacy_style_id" = '1fuop_fOoWTtSSbc_Z4ek' THEN 'ZdIps852qI33hnS31TtAC'
    WHEN "legacy_style_id" = 'M5jLQ3VGzUwZxSeWMErzu' THEN 'nCbYHFlpshesqRlwu86OQ'
    WHEN "legacy_style_id" = 'RdQiDvME_rHfOLYurSTZp' THEN 'rq83H3XNXBQAKgsmvK7n5'
    WHEN "legacy_style_id" = 'EO6c9w1j8xQ5Lhh9RpDxu' THEN 'PTDtZYKBgWWfwFPCL1T1T'
    WHEN "legacy_style_id" = 'Wsuqmczf7mJmSJWwOS5Ak' THEN 'rNQu3kfc8kLQkLxSrjDtL'
    WHEN "legacy_style_id" = 'gI9ko6b7VG8TmR8rWsH3U' THEN 'K3pV5AZqZlUkVi7kYI8b8'
    WHEN "legacy_style_id" = 'hLSth6EKeI6glB69aqLNY' THEN '0BSUuPbCwRQiAPxrPFsHe'
    WHEN "legacy_style_id" = 'nMj7kMiHuS99gVds0CHMf' THEN 'E1vWQwVzV2JrhEghxAV7p'
    WHEN "legacy_style_id" = 'HF7nsj9HBBQdj9R9RT6Q4' THEN '-9Tp14FXypEOXKts8iSAq'
    WHEN "legacy_style_id" = '7DO3CiW4sUKWNX4QiaXOF' THEN 'KyA3Dds-rY8RK26KmSger'
    WHEN "legacy_style_id" = 'f5oJtCbcpOVRDFQZhnl0p' THEN '_XibKXQ6SMCEccp1LZWUF'
    WHEN "legacy_style_id" = '64YPlF1nUyRFCv7pZQKoy' THEN '-nC4GpuLsfkFSDEQGREwA'
    WHEN "legacy_style_id" = 'fymeoUdYFAxOAaWTY9zc9' THEN 'uZI1-hMu8lb8jkQgov_7t'
    WHEN "legacy_style_id" = 'iYXeAmHg98ko-KrSidGb5' THEN 'reIiojLBKdyCzBinObBDr'
    WHEN "legacy_style_id" = 'kNCVmR56oHtDvBduX_R0B' THEN 'ZdIps852qI33hnS31TtAC'
    WHEN "legacy_style_id" = 'gSOyu_VBUQ6H8_I4R9lO-' THEN 'nRXXJgZS4ZuHKDk5SiE-Y'
    WHEN "legacy_style_id" = 'gaYGS4mr3AY-WkiRNeQ6S' THEN 'fj5M69e9iROkKV2cF-0SV'
    WHEN "legacy_style_id" = 'rdznVD-yehVTPq6hUvBp1' THEN 'nRXXJgZS4ZuHKDk5SiE-Y'
    WHEN "legacy_style_id" = '3i1SGH1pyWOmBTHSjle_i' THEN '-1HWiWEgoaNZzBN4CE1If'
    WHEN "legacy_style_id" = 'OSqLrkFC5xjcosnfiMLbO' THEN 'T4V6kKroTHI_VuAF8gXtk'
    WHEN "legacy_style_id" = 'yXD_7_Kcb-vFCD6ofkFQu' THEN 'rOBNX8q7Q79eiuFRQzvlf'
    WHEN "legacy_style_id" = 'YqWShxjPPYE120g_H-wHL' THEN 'Gt0vb7pdFhOVIK39rgn7C'
    WHEN "legacy_style_id" = '_H6nUiBQgxWUZk2uJP5Uc' THEN 'EFC2hVnyDItOUGIG5lL4g'
    WHEN "legacy_style_id" = 'hJzaQUTJRfIp3YVLXo8ES' THEN 'VEKn-i-4rE1zIe4OzSiY1'
    WHEN "legacy_style_id" = 'OvmoK4UGkQknmtI9_Kljx' THEN 'dbrkuRXF-IUIqL405T6Rm'
    WHEN "legacy_style_id" = 'v7R1KjzIsHiQ7_QJGls3o' THEN 'uXead90Msna5EWPbvA7v8'
    WHEN "legacy_style_id" = 'Rwo6F5IVzm_BUyx3vhuxN' THEN 'q_BKms9JQCczJ__fDzqtl'
    WHEN "legacy_style_id" = 'F_C1L4sbBYJPyrxwxS5Gx' THEN 'riPUbL0wHDdCaveKR6Hy0'
    WHEN "legacy_style_id" = 'Q6rnjR2WLiRVb-XCf0NkS' THEN 'RPZiHrfIOEWM9E3FvTNyB'
    WHEN "legacy_style_id" = 'PwQ_cSfnZg_HNU4xbUAU1' THEN 'bksiD0zoSr1JZWDH8izIO'
    WHEN "legacy_style_id" = 'bzD6_Lr-kNSNkZsyqC5Cv' THEN 'LzCRpcMHukDouSLhitlXO'
    WHEN "legacy_style_id" = 'w1DddcnBOKIzed0ORDE1F' THEN 'uXead90Msna5EWPbvA7v8'
    WHEN "legacy_style_id" = '_IpeW0P4vJ8YXBqAWbbaE' THEN 'YFtutxIjok24G2XF3Ec5G'
    WHEN "legacy_style_id" = 'cssXxeRWlXY7_iHJddoee' THEN 'T4V6kKroTHI_VuAF8gXtk'
    WHEN "legacy_style_id" = 'oySJAhyhaDYkwZQGEF61E' THEN 'T4V6kKroTHI_VuAF8gXtk'
    WHEN "legacy_style_id" = '18aDuIO0xSERPUWYUi1GZ' THEN 'zCX1379w3Xa9OtmG3xbYL'
    WHEN "legacy_style_id" = '1Plfs_uGpTBvAX0TvfV2u' THEN 'tvPeFLr-NcV8psLfGahOG'
    WHEN "legacy_style_id" = 'vh6juuY5WMJ3X7GKT9ZDe' THEN 'Dz0ZqLiL7FpDLoKYCkDQ6'
    WHEN "legacy_style_id" = '6bLqnQ-n8t2Ss0bxCUWGB' THEN 'v0N8VJnIZlP2_JMtX9jNz'
    WHEN "legacy_style_id" = 'QhE3QPnq8V3kZHUd2dgNk' THEN 'Nr2grQkp2RItmZYdqo5ep'
    WHEN "legacy_style_id" = 'pjV7n0pohsKoi2nt9BX-x' THEN 'WDMwlVpdqri_rxpFbkAWg'
    WHEN "legacy_style_id" = 'gmVU3I1b7A2XgGy76r05h' THEN 'FNyzP2P0kBXKorV8MKHig'
    WHEN "legacy_style_id" = 'pJkvrwsMIM1pVGqZuju65' THEN 'nCbYHFlpshesqRlwu86OQ'
    WHEN "legacy_style_id" = '0c2wka49xtVtLyZSEHPOh' THEN 'EGvZ7N6ozzzleP0NlAtpt'
    WHEN "legacy_style_id" = 'GLG4R48IKpCqHMfrsk7n2' THEN 'NI-gVSXRzyPMYn4Jj1CD2'
    WHEN "legacy_style_id" = 'p1nmuQ2lA6LByJQ-WrCS0' THEN 'tyaTd14z-zOqZrwkJIN9W'
    WHEN "legacy_style_id" = 'BqE-00ezoLOTW-0PME_4_' THEN 'nCbYHFlpshesqRlwu86OQ'
    WHEN "legacy_style_id" = '6DMC7TrUZesXpsMAiFCgp' THEN 'km93mn3OEWd_CJxsULd8l'
    WHEN "legacy_style_id" = 'HLXNlljB9Nl-50Ca22VUV' THEN 'rNQu3kfc8kLQkLxSrjDtL'
    WHEN "legacy_style_id" = 'MfEUv4A0xNIrOmKNEvmzc' THEN 'J-EUepQtz2Db_er5cTtoW'
    WHEN "legacy_style_id" = 'z5F8VD3FL4gbl9o2zznau' THEN 'rNQu3kfc8kLQkLxSrjDtL'
    WHEN "legacy_style_id" = '91k_DsGHptFMDhzV4XIUQ' THEN '-nC4GpuLsfkFSDEQGREwA'
    WHEN "legacy_style_id" = 'nu_O2c7F9sJmrKaYdfhpn' THEN 'K3pV5AZqZlUkVi7kYI8b8'
    WHEN "legacy_style_id" = 'TnGQuenj6ZzNPfN3PdQc1' THEN 'uZI1-hMu8lb8jkQgov_7t'
    WHEN "legacy_style_id" = '0dLeOXjVXkmRskIowobhO' THEN 'gdWRQ4g9lfObQF4e1H6yx'
    WHEN "legacy_style_id" = 's-TzHl3zWlaFMN5wo3SM9' THEN 'hnQwpOkuK0ILYSrvMayXg'
    WHEN "legacy_style_id" = '31FjH6JC9ho-6UbwB-V0Q' THEN 'qCnQufzY_89iWnzDenr38'
    WHEN "legacy_style_id" = 'HmUcY1kqBODNBI-UK89uR' THEN 'hFJObgVyNWnIqt_OxdXZM'
    WHEN "legacy_style_id" = 'Mt7mC3ZlzQfL3fpZczfS_' THEN 'Q2uXfYlxpoDzrMiT1RZoe'
    WHEN "legacy_style_id" = 'MjI0r6oWFDbw0nmTiG_pk' THEN '0jo2tC38FDV1rjB3nqFYg'
    WHEN "legacy_style_id" = 'v0sd6kkoDZOtLdWwz8iRh' THEN 'csdf5oCv7NlJ60iRDsjp2'
    WHEN "legacy_style_id" = '6-Ic8fEn9YWbN20cd8U8h' THEN 'hB18FlBPo2H2d0a5mDtlP'
    WHEN "legacy_style_id" = 'CTq9HVsOJRNg-z9fVRzoy' THEN 'Je2qvU5kHgWsZKgUUDRgZ'
    WHEN "legacy_style_id" = 'lzVctqEtlyIRGyOd9G71F' THEN 'CBpO2pnHNT8L1tjzBSY1G'
    WHEN "legacy_style_id" = 'U2NHI4WXI11-qUQqpzUcw' THEN 'xkqidfk6C9TEB0JFVDF-A'
    WHEN "legacy_style_id" = 'hWwjB2c3TUM7cta4zfgax' THEN 'yed4mMDDVVND6vdmL9Del'
    WHEN "legacy_style_id" = 'VHEQpikhlf_csaPvt0zyi' THEN 'Nr2grQkp2RItmZYdqo5ep'
    WHEN "legacy_style_id" = 'wQRPbvAnfSJ9dXAA96wL-' THEN 'R92_0K4bi7dZrLWayDbXq'
    WHEN "legacy_style_id" = 'YcExnKoypjITW8I2FJpo8' THEN 'kKT5J8M8XawIUGpTgYK4O'
    WHEN "legacy_style_id" = 'Lb48FX9b5UYHdKZQJj2N7' THEN '-agdF-8Smj8G3HKhqIjzF'
    WHEN "legacy_style_id" = '05NO8etsw_5fAw7sHIoBW' THEN 'oUpWohhyZwr8w4xk_5qZQ'
    WHEN "legacy_style_id" = 'Z1eXiCe_T6vEzFtlrscVE' THEN 'J-EUepQtz2Db_er5cTtoW'
    WHEN "legacy_style_id" = 'zwNmXSGm3ZYJ47hF4XdVN' THEN 'vsk8kU2ghfnnkJlZ6mq0M'
    WHEN "legacy_style_id" = 'WDp65wOD_5a258mbmJ1X0' THEN '1k5sCtMvBGVdE1M6de4a6'
    WHEN "legacy_style_id" = '-emBheUn-nZOe5EPFvF6w' THEN 'riPUbL0wHDdCaveKR6Hy0'
    WHEN "legacy_style_id" = 'RCIpq0UMkHiVVvIOYXn0Z' THEN '9rrTPIGqrvAlGGbtOuZem'
    WHEN "legacy_style_id" = 'M30AZni5AOdqSLHRRxqIh' THEN 'PTDtZYKBgWWfwFPCL1T1T'
    WHEN "legacy_style_id" = 'iSrUxHA4hC3fIkvRVAotI' THEN 'f0iMUkt3GpDJ6kzNn-krK'
    WHEN "legacy_style_id" = 'qbinyrZQyIZpZvq3Z3WDb' THEN 'SqsEQI0F2UFdX-CcClF2d'
    WHEN "legacy_style_id" = '6drug607QSPZYUHyGkD-g' THEN 'oUpWohhyZwr8w4xk_5qZQ'
    WHEN "legacy_style_id" = '_o6DMux6Ijhva76qobiup' THEN '1k5sCtMvBGVdE1M6de4a6'
    WHEN "legacy_style_id" = 'N-ZtI6jYJsUjvSAhkE1Qi' THEN 'dZ-8UvZ1ALtNLAKTMoUEs'
    WHEN "legacy_style_id" = 'qF3H-5J4FRaCLQDVf8Usw' THEN 'mt5cuwYIyIhUJhKoHWLdV'
    WHEN "legacy_style_id" = 's2rCGXxtj0B-EYROCrWxF' THEN '5lXaVXAfDqpp7bs6cdcXb'
    WHEN "legacy_style_id" = 'QoCNHmUV2cX8dFft4sxDK' THEN 'u1cxWHxam3zHReKr6ybRZ'
    WHEN "legacy_style_id" = '7zceip2BPgIT9KlSSfURR' THEN 'w2RPOGlGR7JXCSulKQKRQ'
    WHEN "legacy_style_id" = '1FbtBS12Ifo7tpwGW-Plj' THEN 'af2n2-58b2aQ6cg61b8LI'
    WHEN "legacy_style_id" = 'zmBioFHpFJQxZ7gqwC4Jo' THEN 'dbrkuRXF-IUIqL405T6Rm'
    WHEN "legacy_style_id" = 'O4wswMjvZi6sTlWXKlhp3' THEN 'Vl_m6EI0hPiUwaZz8YC6E'
    WHEN "legacy_style_id" = 'e__ir9aW9uQ5ZIAcQ6OMo' THEN '-nC4GpuLsfkFSDEQGREwA'
    WHEN "legacy_style_id" = 'KU1cNfIl1DaOp7fUHnkTc' THEN '5SUflyx0b1ApAQOnbGyzY'
    WHEN "legacy_style_id" = 'TjFkepboAz3Okh3DpHMt1' THEN '5SUflyx0b1ApAQOnbGyzY'
    WHEN "legacy_style_id" = 'cxrxQw2bx-OUDzUoBorFY' THEN '7B3gL6yBWAFLSa6lnq5f8'
    WHEN "legacy_style_id" = '-DAORcSFlLbmehOAx03ZP' THEN 'ZRpAXRBex8EM96v9_2wna'
    WHEN "legacy_style_id" = '2QL3V_gWAHKkJYtRss7sq' THEN '7B3gL6yBWAFLSa6lnq5f8'
    WHEN "legacy_style_id" = 'oi2q0PdwHrDqplAws5eEN' THEN 'hFJObgVyNWnIqt_OxdXZM'
    WHEN "legacy_style_id" = 'JqsaeYIGqI55rHfEb6G-D' THEN 'yed4mMDDVVND6vdmL9Del'
    WHEN "legacy_style_id" = 'PO02VXatCKWV034TSk6jw' THEN 'onfMHIo3mVEgVfAicUDIV'
    WHEN "legacy_style_id" = 'Br3WgnTvb-m0Eb748m5A9' THEN 'hWKk1NCdWgtp0zxQGdpoe'
    WHEN "legacy_style_id" = 'SCWajukHiHn1v17VZydJE' THEN '5lXaVXAfDqpp7bs6cdcXb'
    WHEN "legacy_style_id" = 'J-ad2C59a2BsF6tYNsA1E' THEN '9rrTPIGqrvAlGGbtOuZem'
    WHEN "legacy_style_id" = 'LL6jbEy33RpKrko-6lLKt' THEN 'qaqKVgpkEh2hWD4GFcHUD'
    WHEN "legacy_style_id" = 'rOq6CqF_4faVrIF3bi27k' THEN '9JRqVqb-ctkE_HKni7Brl'
    WHEN "legacy_style_id" = 'qQ7O3gqT6MEEKiHkVbRAY' THEN 'rTE5rRI4bisgWZCoecDld'
    WHEN "legacy_style_id" = 'Jq0kAy9Cocmu5L9-XnFGP' THEN 'T4V6kKroTHI_VuAF8gXtk'
    WHEN "legacy_style_id" = 'mGxWpT4gz78KW4yD_69zP' THEN 'onfMHIo3mVEgVfAicUDIV'
    WHEN "legacy_style_id" = '9Yc75wtZ8R0ZQl7QVxjGP' THEN 'FvU_z2tmoO8pX5mgszCOw'
    WHEN "legacy_style_id" = 'Z7FTvPUokuSDBzN-cL4Lc' THEN '8LBAdBfUMsSOCPG-W6KDs'
    WHEN "legacy_style_id" = 'MXs166aYV6Zc4nKgQcZRB' THEN 'uZi1PwndtwWLGFpoOpzsK'
    WHEN "legacy_style_id" = 'AlYVT7Lb_AhV8ZmWytHgK' THEN 'AAeoV8sOzitGRMsDE4f2Z'
    WHEN "legacy_style_id" = 'hAbCRynSn3u3cywpL19n5' THEN 'uZi1PwndtwWLGFpoOpzsK'
    WHEN "legacy_style_id" = 'EBMYZ1EdPQ-UaHk-mTGjW' THEN 'XhyN5dz87T1qzNABd2Rky'
    WHEN "legacy_style_id" = 'VSZdnmoTidq7MMgxwh9Dt' THEN 'uZi1PwndtwWLGFpoOpzsK'
    WHEN "legacy_style_id" = 'TG89iRQyjYvvncbxok4GH' THEN 'XhyN5dz87T1qzNABd2Rky'
    WHEN "legacy_style_id" = 'bMaGbmW5uQQF9Gq775rjO' THEN 'xkqidfk6C9TEB0JFVDF-A'
    WHEN "legacy_style_id" = '9W7P2Q3aaX0N6NZmycrGJ' THEN 'rOBNX8q7Q79eiuFRQzvlf'
    WHEN "legacy_style_id" = 'aXQMPBQQ7I6lSEtzzl8XP' THEN 'XxofBZ-loLzoaKgq5AxVH'
    WHEN "legacy_style_id" = '54GAJFsJe-e4zKzVj8Z_U' THEN 'Dz0ZqLiL7FpDLoKYCkDQ6'
    WHEN "legacy_style_id" = 'QxcJQjZqeVrHlPHRYuLJt' THEN 'AXrHELPTdk9ucLJ0hnkEI'
    WHEN "legacy_style_id" = 'imgwrnOEJxK3FTkUQOHg0' THEN 'yed4mMDDVVND6vdmL9Del'
    WHEN "legacy_style_id" = 'TvEuO8cVPFB1kHxYNs2D2' THEN 'Ir0vcypVPwL6EVbH2O4A3'
    WHEN "legacy_style_id" = 'ZPZKxJTT51qwEUnIzN-pY' THEN 'H4bUfD41MWxPK7SYolEqH'
    WHEN "legacy_style_id" = 'U6Hsho_ijPWjnAsiW9ZdB' THEN 'ET_bRl_DKg7hYhl1qg4Za'
    WHEN "legacy_style_id" = 'mTAonBKf1FsOYGpy-Z2cs' THEN 'E1vWQwVzV2JrhEghxAV7p'
    WHEN "legacy_style_id" = 'UDMleCneQPYObwem_ndId' THEN 'KQ8ezXHu7cio3D8YuC-iv'
    WHEN "legacy_style_id" = 'dRu-i-703r0L_vhbGzu3D' THEN 'KQ8ezXHu7cio3D8YuC-iv'
    WHEN "legacy_style_id" = '-cDL5GtJ0zYpFux-UtLTx' THEN 't2VfLg_m7Ua0-axxP-4XJ'
    WHEN "legacy_style_id" = '5za87kVyYYDVWCHmVTtUB' THEN 'KQ8ezXHu7cio3D8YuC-iv'
    WHEN "legacy_style_id" = '-UxqQbmCDr0WMGs8uEtYv' THEN 'vsk8kU2ghfnnkJlZ6mq0M'
    WHEN "legacy_style_id" = 'DLxo6YoHeHKJhXpJsdafp' THEN 't2VfLg_m7Ua0-axxP-4XJ'
    WHEN "legacy_style_id" = 'jnlSTi9uFPhJePH6-mE-e' THEN 't2VfLg_m7Ua0-axxP-4XJ'
    WHEN "legacy_style_id" = 'IEmkWA2xjK6qPq4FyM8ai' THEN 'CDPP1nEUZFVUAXiYKGvis'
    WHEN "legacy_style_id" = 'TcVycpj_USSa5j5FJ9QAk' THEN 'g0ySyTa0Zi6zTGhSbTzSh'
    WHEN "legacy_style_id" = 'PliD4Z-OqppiYp3Z03K_4' THEN '7zWYA_xskIc9R_Lqs9bAm'
    WHEN "legacy_style_id" = 't9fwIpNRtd1v69Ih07V_a' THEN 'hnQwpOkuK0ILYSrvMayXg'
    ELSE style_id
  END;

-- AlterTable
ALTER TABLE "beer_data"."beers" ALTER COLUMN "style_id" SET NOT NULL;

-- AlterTable
ALTER TABLE "beer_data"."beers" DROP COLUMN "legacy_style_id";

COMMIT;
